"""initial schema

Revision ID: 5d3a21d3bffb
Revises: 
Create Date: 2026-08-22 16:09:43.455195

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d3a21d3bffb'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=True),
    sa.Column('rate_limit_custom', sa.Integer(), nullable=False),
    sa.Column('rate_limit_custom_refill', sa.Integer(), nullable=True),
    sa.Column('request_count_lifetime', sa.BigInteger(), nullable=False),
    sa.Column('allowed_ips', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('admin_key_hash', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_admin_key_hash'), 'audit_events', ['admin_key_hash'], unique=False)
    op.create_index(op.f('ix_audit_events_resource'), 'audit_events', ['resource'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=512), nullable=False),
    sa.Column('fallback_url', sa.String(length=512), nullable=True),
    sa.Column('strip_prefix', sa.Boolean(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('allowed_methods', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_prefix'), 'routes', ['prefix'], unique=True)
    op.create_table('tier_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('current_tier', sa.String(length=64), nullable=False),
    sa.Column('requested_tier', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tier_requests_user_id'), 'tier_requests', ['user_id'], unique=False)
    op.create_table('tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('refill_rate', sa.Float(), nullable=False),
    sa.Column('window_info', sa.String(length=32), nullable=False),
    sa.Column('monthly_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiers_name'), 'tiers', ['name'], unique=True)
    op.create_table('usage_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('requests', sa.BigInteger(), nullable=False),
    sa.Column('bytes_in', sa.BigInteger(), nullable=False),
    sa.Column('bytes_out', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'route', 'day', name='uix_usage_daily_user_route_day'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_usage_daily_day'), 'usage_daily', ['day'], unique=False)
    op.create_index(op.f('ix_usage_daily_route'), 'usage_daily', ['route'], unique=False)
    op.create_index(op.f('ix_usage_daily_user_id'), 'usage_daily', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_daily_user_id'), table_name='usage_daily')
    op.drop_index(op.f('ix_usage_daily_route'), table_name='usage_daily')
    op.drop_index(op.f('ix_usage_daily_day'), table_name='usage_daily')
    op.drop_table('usage_daily')
    op.drop_index(op.f('ix_tiers_name'), table_name='tiers')
    op.drop_table('tiers')
    op.drop_index(op.f('ix_tier_requests_user_id'), table_name='tier_requests')
    op.drop_table('tier_requests')
    op.drop_index(op.f('ix_routes_prefix'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_audit_events_resource'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_admin_key_hash'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
