{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "gateflow.fullname" . }}-secrets
  labels:
    {{- include "gateflow.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "gateflow.fullname" . }}-secrets
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        ADMIN_KEY: "{{ `{{ .admin_key }}` }}"
        KEY_SECRET: "{{ `{{ .key_secret }}` }}"
        WEBHOOK_SIGNING_SECRET: "{{ `{{ .webhook_signing_secret }}` }}"
  data:
    - secretKey: admin_key
      remoteRef:
        key: {{ .Values.externalSecrets.references.adminKey }}
    - secretKey: key_secret
      remoteRef:
        key: {{ .Values.externalSecrets.references.keySecret }}
    {{- if .Values.externalSecrets.references.webhookSigningSecret }}
    - secretKey: webhook_signing_secret
      remoteRef:
        key: {{ .Values.externalSecrets.references.webhookSigningSecret }}
    {{- end }}
{{- end -}}
