{{- if and .Values.secrets (not .Values.externalSecrets.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateflow.fullname" . }}-secrets
  labels:
    {{- include "gateflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
{{- end -}}
