apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: gateflow
  namespace: gateflow
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateflow
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: gateflow
  service:
    port: 80
    targetPort: 8000
    gateways:
      - gateflow
  analysis:
    interval: 30s
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
      - name: request-duration
        thresholdRange:
          max: 500
    webhooks:
      - name: load-test
        type: pre-rollout
        url: http://flagger-loadtester.test/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://gateflow-canary.gateflow/health"
